### ISSUE TITLE
Feature Request: Open AI API Support

### ISSUE THREAD

**Issue by dangero2000** [hxebolax/TranslateAdvanced#10]
Open AI's GPT is able to translate between languages fairly decently with few problems. Open AI also has an API platform that can be used in applications and add-ons such as this one. It would be great if we could use this API platform as a translate service within the add-on.
I'm not sure how difficult this might be, considering that you don't really set source and target languages, but rather system prompts telling the AI what you want it to do with the user's input. While GPT is capable of translation, that's not its primary feature. It doesn't really have a primary feature strictly speaking; it's a multipurpose tool, which is why it needs to be instructed. That being said, I would be happy to have a go at writing a system prompt and helping you test this implementation if you aren't familiar with how the Open AI API works.

**Comment by hxebolax** [comment]
Hello, thank you for your suggestion.
I want to inform you that this feature will be implemented in future versions.
I am familiar with it as I work with the OpenAI platform and its API.
I already have the module for translating with OpenAI done and functional, but I want to add it after certain features that I want to implement first since this module will complement some of those features.
I want to finish stabilizing the add-on once it is released for everyone, addressing the errors that have arisen. Then, we will be able to use OpenAI as a translator without external libraries, which is another of my intentions: not to use third-party libraries and only use the NVDA ecosystem. In this case, direct calls to the API with URLIB.
The request remains open until it is implemented in future updates.
Thank you.

**Comment by dangero2000** [comment]
I cannot describe how grateful I am that you're considering this. I am bilingual, and part of my study plan is having Open AI translate words into both languages so I can study and understand individual words. After this feature is implemented, it'll make it significantly easier to study this way. So, I thank you. I would happily donate to you if you have an option to do that anywhere.
