### ISSUE TITLE
Strange problem with apostrophes when using Google Translate (web)

### ISSUE THREAD

**Issue by Shadowcat42** [hxebolax/TranslateAdvanced#13]
When using the realtime translation mode of the addon and Google Translate (web 1 or 2), if an apostrophe is in the resulting translated text, it appears as "&#39;". Strangely, however, this only applies to those two specific modules. The Google translate free API modes do not have this problem, though I am not sure what the difference is between these two things. This is using NVDA 2024.3.1, and Advanced Translator 2024.09.07.
Thank you.

**Comment by hxebolax** [comment]
Hello, thank you for the information and the notice.
I would appreciate it if you could try this version where I attempt to fix the problem with the two modules you mentioned.
https://xebolax.synology.me/compartir/indice/Caj%C3%B3n%20desastre/TranslateAdvanced_2024.09.07.nvda-addon
It's the same official version as the one in the store, but with a patch applied for the two Google translation modules via web.
The difference with the others is the way the translation is obtained: one is through web scraping, which is causing the issues you're having, and the others are via API.
In case the problem is not solved, I would like to ask you if you could send me an example of a phrase where the issue occurs, along with the target language you are trying to translate it into.
English is not my first language, so I don't usually use the apostrophe, which means I cannot easily replicate the issue, and I'm not sure if the patch, which addresses changes Google has made to the web, will fix your problem.
If it is fixed, these patches will be included in the next version.
Thank you very much.

**Comment by Shadowcat42** [comment]
Hello,
I did some more testing with the new version. I also did not notice that in my actual post, it actually gave a proper apostrophe. What is appearing is \&#39;, which I assume is the actual character code of an apostrophe. Sorry about that, I should've previewed before sending.
What I forgot to mention in the original post was that this only happens with the realtime translation mode. If manually translating through the interface or through the layer menu, this issue does not appear at all.
The new patch does not fix the issue with the realtime translation mode, unfortunately. And I did deactivate the translation cache before testing.
What may also be helpful or not is that the glitched character also appears in the translation history dialogue, so you can see it for yourself there.
My target language is English, so here are two things that should produce consistent results. The length of the string does not seem to matter, as this happens while translating longer strings as well.
marca del cazador
老虎的吼
Thank you.

**Comment by hxebolax** [comment]
Hello, I believe I’ve found the issue, which was that I wasn’t properly escaping the received input.
I would like you to test this version now, as it seems that in the tests I’ve done, the problem is already solved.
If the results are positive, as I mentioned, this will appear in the next version. Given the nature of the issue, it won’t take long to release it, as it’s quite annoying for English-speaking users.
https://xebolax.synology.me/compartir/indice/Caj%C3%B3n%20desastre/TranslateAdvanced_2024.09.07.nvda-addon
Thank you very much.

**Comment by Shadowcat42** [comment]
No, thank you for the quick fix. 👍 Seems to be working fine now.
