### ISSUE TITLE
El complemento no detecta la conexión a Internet

### ISSUE THREAD

**Issue by dangero2000** [hxebolax/TranslateAdvanced#8]
Hola,
Estoy conectado a Internet usando wi-fi. Por alguna razón, Advanced Translate no detecta mi conexión, a pesar de que estoy utilizando activamente Internet en otras aplicaciones e incluso en otros complementos. He reiniciado NVDA varias veces e incluso he eliminado muchos complementos que no estaba utilizando. No importa lo que haga, este complemento específico no puede reconocer mi conexión a Internet. Una solución potencial podría ser no verificar la conexión hasta que NVDA se cargue por completo, o solo verificar cuando se intente una traducción.
Si esto ayuda, no tengo una tarjeta wi-fi en mi computadora, y, por lo tanto, tengo que usar mi teléfono Android como un anclaje USB. Tal vez el propio complemento no pueda reconocer ciertos tipos de conexión.
Traducido con Chat GPT.

**Comment by hxebolax** [comment]
Hello, it would be good if you could send me what the log says after restarting NVDA and ensuring that you have an internet connection.
The bridge between the mobile and the computer is not an impediment. In fact, at work, I connect this way by sharing my mobile's internet connection with the computer, and I have no problem.
At home, both with Wi-Fi and cable, neither is an issue, and this is the first report of this type that I have received.
In essence, I need the log, and the plugin will not get a connection if NVDA does not have one; therefore, it is not a plugin issue.
As I said, it is being used correctly in many cases without problems.
Please send me the NVDA log from its first startup and then several subsequent startups of NVDA so that we can try to figure something out.
 
If you need any further assistance or adjustments, feel free to ask!

**Comment by dangero2000** [comment]
For sure, I will upload the logs.

A few notes on the logs:

- Log 1 is my normal NVDA setup
- Log 2 is after I fixed a lot of the errors that I could fix with other addons and disabled the original Translate addon from Yplassiard
- Log 3 is after I deleted old config directories
- Log 4 is a normal restart with no other changes made

Next, I'm going to try to make a portable NVDA installation with every addon accept Advanced Translate deleted, adding each addon back one at a time to see which ones break this one. This will take me some time to do. In the meantime, I hope these logs help to trace the issue.
[log1.txt](https://github.com/user-attachments/files/16040328/log1.txt)
[log2.txt](https://github.com/user-attachments/files/16040329/log2.txt)
[log3.txt](https://github.com/user-attachments/files/16040330/log3.txt)
[log4.txt](https://github.com/user-attachments/files/16040331/log4.txt)

**Comment by dangero2000** [comment]
Update: I have tried uninstalling every addon, but to no effect. I also installed the English version of NVDA as a portable copy with Advanced Translate, and it still didn't work. It's worth noting that I was using Tela NVDA (an NVDA Remote derivative) at the same time before, so NVDA can definitely connect to the internet. For some reason, this addon can't on my machine.

**Comment by hxebolax** [comment]
Hello, I would like you to try out this version if possible.
It's exactly the same, but I've disabled the internet existence check.
I want to see if it's the internal function within the add-on that might cause errors in some connections during the check.
Let me know your thoughts.

https://xebolax.synology.me/compartir/indice/Caj%C3%B3n%20desastre/TranslateAdvanced_2024.06.23_not_connection.nvda-addon

Regards

**Comment by dangero2000** [comment]
Thank you for the link. The addon now works flawlessly.

**Comment by hxebolax** [comment]
Hello, thank you very much for trying.
In the next version coming out this month, I hope the new way to check for internet connectivity works for you.
It is already implemented in the code and, as I mentioned, it will come in the new version, replacing the method that wasn't working for you.
I will use something more universal to see if there are no more problems.
I will leave the Issue open so that when the next version comes out, you can let me know if it works.
And I will close it if everything is correct.
Thank you very much.

**Comment by dangero2000** [comment]
I can confirm that the new method works flawlessly. Much appreciated! 👍
